proyecto_vacaciones/urls.py
from django.urls import path,include
from django.contrib import admin
from usuarios.views import HomePageView,RevistaPageView,MangaPageView,Descrip_libPageView,AutoresPageView,RegistrarView
from django.views.generic.base import TemplateView

urlpatterns = [
   path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
   path('Home',HomePageView.as_view(), name='home'),
   path('Manga',MangaPageView.as_view(), name='mangas'),
   path('Revista',RevistaPageView.as_view(), name='revistas'),
   path('descrip_lib',Descrip_libPageView.as_view(), name='descrip_lib'),
   path('Autor',AutoresPageView.as_view(), name='Autores'),
 path('registrar/', RegistrarView.as_view(),name='registrar'),


]

usuarios/urls.py
from django.urls import path
from .views import HomePageView,RevistaPageView,MangaPageView,Descrip_libPageView,AutoresPageView,DetallePageView,CrearPageView,UpdatePageView,DeletePageView,RegistrarView,ComentarioCreateView
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


urlpatterns=[
        path('',HomePageView.as_view(),name='home'),
     path('mangas',MangaPageView .as_view(),name='mangas'),
      path('revistas',RevistaPageView.as_view(),name='revistas'),
      path('descrip_lib',Descrip_libPageView.as_view(),name='descrip_lib'),
      path('Autor',AutoresPageView.as_view(),name='Autores'),
       path('Nombre/<int:pk>/editar',DetallePageView.as_view(),name='descAutores'),
    path('Nuevo/Autor',CrearPageView.as_view(),name='CrearAutores'),
     path('Nombre/<int:pk>/Update',UpdatePageView.as_view(),name='EditAutores'),
      path('Nombre/<int:pk>/delet',DeletePageView.as_view(),name='deleteAutores'),
    path('registrar/', RegistrarView.as_view(),name='registrar'),
      path('Comentarios/<int:libroComent>',ComentarioCreateView.as_view(),name='comentarioNuevo'),
   
    path('password_reset/', PasswordResetView.as_view(
        template_name='registration/password_reset.html'
    ),name='password_reset'),

   path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'
    ),name='password_reset_done'),

   path('usuarios/password_reset_confirm/<u1db64>/<token>', PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html'
    ),name='password_reset_confirm'),

path('usuarios/password_reset_complete', PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
    ),name='password_reset_complete'),

]

usuarios/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings
from django.urls import reverse


# Create your models here.

class UsuarioPers(AbstractUser):
    edad = models.PositiveIntegerField(null=True, blank=True)
    telefono = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    genero = models.CharField(null=True,blank=True, max_length=1)


class Post(models.Model):
    text = models.TextField(default="")
    descrpicion = models.TextField(default="")
    img = models.TextField(default="")
   
    def __str__(self):
        return self.text
   

class Manga(models.Model):
    text = models.TextField(default="")
    descrpicion = models.TextField(default="")
    img = models.TextField(default="")
   
    def __str__(self):
        return self.text

    

class DescripLib(models.Model):
    text = models.TextField(default="")
    descrpicion = models.TextField(default="")
    img = models.TextField(default="")
    presio = models.TextField(default="")
   
    def __str__(self):
        return self.text

class Autores(models.Model):
    Nombre = models.TextField(default="")
    Descripcion = models.TextField(default="")
    img = models.TextField(default="")
    Nacionalidad = models.TextField(default="")
    F_Muerte = models.TextField(default="")
    autor = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return self.Nombre

    def get_absolute_url(self):
        return reverse('', args=[str(self.id)])

class Comentario(models.Model):
    comentario = models.CharField(max_length=300)
    autor = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE,
        related_name='comentario'
        )
        
    def __str__(self):
        return self.comentario
    

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UsuarioPers

class UsuarioPersCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = UsuarioPers
        fields = UserCreationForm.Meta.fields + ('edad','telefono','email','genero',)

class UsuarioPersChangeForm(UserChangeForm):
    class Meta:
        model = UsuarioPers 
        fields = UserChangeForm.Meta.fields

usuarios/views.py
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from .models import Post,DescripLib,Manga,Autores,Comentario
from .forms import UsuarioPersCreationForm
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied





class HomePageView(ListView):
    template_name = 'home.html'
    model = Post
    context_object_name='Listado'
    
class RegistrarView(CreateView):
   form_class = UsuarioPersCreationForm
   success_url = reverse_lazy('login')
   template_name = 'registrar.html'  

class MangaPageView(ListView):
    template_name = 'mangas.html'
    model = Manga
    context_object_name='Listado1'

class RevistaPageView(ListView):
    template_name = 'revistas.html'
    model = Post
    context_object_name='Listado'

class Descrip_libPageView(ListView):
    template_name = 'descrip_lib.html'
    model = Post
    context_object_name='Listado1'

class AutoresPageView(ListView):
    template_name = 'Autores.html'
    model = Autores
    context_object_name='Listado1'


class DetallePageView(DetailView):
    template_name = 'descAutores.html'
    model = Autores
    context_object_name='Blogs'

class CrearPageView(LoginRequiredMixin,CreateView):
    template_name = 'CrearAutores.html'
    model = Autores
    success_url = reverse_lazy('home')
    fields = 'Nombre','Descripcion','img','Nacionalidad','F_Muerte',
    login_url = 'login'

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)
    
class UpdatePageView(LoginRequiredMixin,UpdateView):
    template_name = 'editarAutores.html'
    model = Autores
    success_url = reverse_lazy('home')
    fields = 'Nombre','Descripcion','img','Nacionalidad','F_Muerte',
    login_url = 'login'

    def form_valid(self, form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

    def dispatch(self, request, *args,**kwargs):
        obj = self.get_object()
        if obj.autor != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

class DeletePageView(LoginRequiredMixin,DeleteView):
    template_name = 'eliminarAutores.html'
    model = Autores
    success_url = reverse_lazy('home')
    context_object_name='Autores'
    login_url = 'login'
    
    def dispatch(self, request, *args,**kwargs):
        obj = self.get_object()
        if obj.autor != self.request.user:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)


class ComentarioCreateView(LoginRequiredMixin,CreateView):
    model = Comentario
    template_name = "comentarioNuevo.html"
    fields = ('comentario',)
    login_url='login'
    success_url = reverse_lazy('home')

    def form_valid(self,form):
        form.instance.autor = self.request.user
        return super().form_valid(form)

templates/Autores.html
{% load static %}
<!DOCTYPE html>
<html>
	<style>
		#texto{
			background-color: rgb(138, 1, 108);
			color: wheat;
		}

	

		#a_1{
			width: 100%;
			height: 100px;
			font-size: 20px;
			text-align: center;
			color: white;
			margin-top: 10px;
		}
		#a_1_1{
			width: 100%;
			height: 100px;
			font-size: 20px;
			text-align: center;
			color: black;
			margin-top: 10px;
		}
		#cont1{
			background-color: black;
			height: 50px;
		
		}

		#btn1{
			height: 130px;
			margin-top: -65px;
			border-style: solid;
		}

		#btn1_1{
			height: 130px;
			margin-top: -65px;
			background-color: yellow;
		}

		#btn1:hover{
			background-color: yellow;
			border-style: none;
		}
		#a_1:hover{
			color: #000;
		}
		#a_1_1{
			background-color: yellow;
		}
		.carousel-inner img{
			width: 100px;
			height: 400px;
		}

		#carouselExampleIndicators{
			width: 1200px;
			margin-left: 100px;
		}
		#promo{
			background-color: rgba(74, 63, 100, 0.363);
			width: 400px;
			height: 450px;
			float: left;
			border-style: solid;
		}
		#home_img{
			height: 200px;
			width: 150px;
			margin-left: 120px;
		}
		#content_lib{
			
			width: 1200px;
			
			margin-left: 100px;
			margin-top: 10px;
			
		}
		#link_desc{
			margin-left: 110px;

		}
		#linea{
			background-color: black;
			height: 40px;
			width: 100%;
			
		}

		#li_titulo_bd{
			font-family: Arial, Helvetica, sans-serif;
			font-size: 20px;
			font-weight: 400;
			text-align: center;
			list-style: none;
			color: black;
		}

        #imagen_1_d{
            padding-top: 50px;
            height: 300px;
            width: 250px;
            
        }
        #div_autores{
            float: left;
            width: 300px;
            border-style: solid;
            padding-left: 20px;
            height: 450px;
            background-color: rgba(221, 245, 8, 0.39);
        }
       
		#btn_a{
            width: 91%;
        }
		#saludo{
			color: white;
			text-align: center;
			margin-top: 20px;
		}
		#logout{
			
			margin-left: 70px;
		}
	</style>
<head>
	<title></title>
</head>

<!--link de css,bootstrap-->
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<body>

	<!--natvar principal-->
	<div class="jumbotron text-center" id="texto">
		<h1>Libreria "Momentos"</h1>
		<p>Encuentra lo que ves en tus sueños!!!!</p>
	  </div>
	  
	  <div class="jumbotron" id="cont1">
		<div class="row" >
		  <div class="col-sm-2" id="btn1">
		   
			 <a id="a_1" type="button" class="btn" href="{% url 'home' %}"><br>HOME</a>
		  </div>
		  <div class="col-sm-2" id="btn1">
			  <a id="a_1" type="button" class="btn" href="{% url 'mangas' %}"><br>MANGAS</a>
		  </div>
		  <div class="col-sm-2" id="btn1">
			  <a id="a_1" type="button" class="btn" href="{% url 'revistas' %}"><br>REVISTAS   </a>
		  </div>
		  <div class="col-sm-2" id="btn1_1">
			  <a id="a_1_1" type="button" class="btn" href="{% url 'Autores' %}"><br>AUTORES</a>
			</div>
			<div class="col-sm-2" id="btn1">
			  <a id="a_1" type="button" class="btn" href="{% url 'login' %}"><br>LOGIN</a>
			</div>

			<div class="col-sm-2" id="btn1">
				{% block contect %}
				  {% if user.is_authenticated %}
					  <h4 id="saludo">Bienvenido {{ user.username }}</h2>
					  <a id="logout" href="{% url 'logout' %}">log out</a>
					  {% endif %}
	  
					  {% endblock contect%}
	  
		  </div>
		  
		</div>
	  </div>

	<!--Inicio de la declaracion del carrusel -->


	<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
		<ol class="carousel-indicators">
		  <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
		  <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
		  <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
		</ol>
		<div class="carousel-inner">
		  <div class="carousel-item active">
			<img class="d-block w-100" src="{% static 'img/13.png' %}" alt="First slide">
		  </div>
		  <div class="carousel-item">
			<img class="d-block w-100" src="{% static 'img/12.png' %}" alt="Second slide">
		  </div>
		  <div class="carousel-item">
			<img class="d-block w-100" src="{% static 'img/11.jpg' %}" alt="Third slide">
		  </div>
		</div>
		<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
		  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		  <span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
		  <span class="carousel-control-next-icon" aria-hidden="true"></span>
		  <span class="sr-only">Next</span>
		</a>
	  </div>



	
<!--fin de la declaracion del carusel -->




<!--muestra los autores ingresados a la base de datos -->
	<div id="content_lib">

     
            <h1> Autores</h1>
            
                <div style="width: 40%;margin-left: 400px;"><a type="button" class="btn btn-primary btn-block " href="{%url 'CrearAutores' %}">Agregar Autor</a></div>
                <br>
            
        
            {%for Autores in Listado1 %}
                <div id="div_autores"> 
                    <div> <img src = {{Autores.img}} id="imagen_1_d">  </div>
                    <div id="div_bajo">
                        
                        <a id="btn_a" type="button" class="btn btn-info " href="{%url 'descAutores' Autores.pk %}">{{Autores.Nombre}}</a><br>
                        <a id="btn_a" type="button" class="btn btn-warning " href="{%url 'EditAutores' Autores.pk %}">Editar {{Autores.Nombre}}</a><br>
                        <a id="btn_a" type="button" class="btn btn-danger " href="{%url 'deleteAutores' Autores.pk %}">Eliminar {{Autores.Nombre}}</a><br>
						<a id="a_1" type="button" class="btn" href="{% url 'comentarioNuevo' Autores.pk %}"><br>Comentar</a>
							
                    </div>
                </div>
                
            {% endfor %}

		
</div>

{% for comentario in autores.comentario.all %}
	<div class="card-footer">
		
		<samp class="font-wigth-bold">{{comentario.autor}}&middot;</samp>
		{{ comentario.comentario}}
	

	</div>
	{%endfor%}

</body>
</html>

templates/editarAutores.html
{% load static %}
<!DOCTYPE html>
<html>
	<style>
		#texto{
			background-color: rgb(138, 1, 108);
			color: wheat;
		}

        p label{
            color: black;
            padding-left: 500px;
           
        }
        p textarea{
            height: 50px;
            width: 500px;
        }
        
        #btn_guardar{
            margin-left: 650px;
            width: 120px;
            height: 50px;
            border-color: rgba(16, 156, 221, 0.829);
            background-color: rgba(16, 156, 221, 0.829);
            color: white;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 18px;
        }

		#a_1{
			width: 100%;
			height: 100px;
			font-size: 20px;
			text-align: center;
			color: white;
			margin-top: 10px;
		}
		#a_1_1{
			width: 100%;
			height: 100px;
			font-size: 20px;
			text-align: center;
			color: black;
			margin-top: 10px;
		}
		#cont1{
			background-color: black;
			height: 50px;
		
		}

		#btn1{
			height: 130px;
			margin-top: -65px;
			border-style: solid;
		}

		#btn1_1{
			height: 130px;
			margin-top: -65px;
			background-color: yellow;
		}

		#btn1:hover{
			background-color: yellow;
			border-style: none;
		}
		#a_1:hover{
			color: #000;
		}
		#a_1_1{
			background-color: yellow;
		}
		.carousel-inner img{
			width: 100px;
			height: 400px;
		}

		#carouselExampleIndicators{
			width: 1200px;
			margin-left: 100px;
		}
		#promo{
			background-color: rgba(74, 63, 100, 0.363);
			width: 400px;
			height: 450px;
			float: left;
			border-style: solid;
		}
		#home_img{
			height: 200px;
			width: 150px;
			margin-left: 120px;
		}
		#content_lib{
			
			width: 1200px;
			
			margin-left: 100px;
			margin-top: 10px;
			
		}
		#link_desc{
			margin-left: 110px;

		}
		#linea{
			background-color: black;
			height: 40px;
			width: 100%;
			
		}

		#li_titulo_bd{
			font-family: Arial, Helvetica, sans-serif;
			font-size: 20px;
			font-weight: 400;
			text-align: center;
			list-style: none;
			color: black;
		}

		
	</style>
<head>
	<title></title>
</head>
<meta charset="UTF-8">
<meta http-equiv="X-UA_Compatible" content="IE-edge">
<meta name="viewport" content="wisth=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<body>

<!--natvar principal-->
	<div class="jumbotron text-center" id="texto">
	  <h1>Libreria "Momentos"</h1>
	  <p>Encuentra lo que ves en tus sueños!!!!</p>
	</div>
	
	<div class="jumbotron" id="cont1">
	  <div class="row" >
		<div class="col-sm-2" id="btn1_1">
		 
		   <a id="a_1_1" type="button" class="btn" href="{% url 'home' %}"><br>HOME</a>
		</div>
		<div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'mangas' %}"><br>MANGAS</a>
		</div>
		<div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'revistas' %}"><br>REVISTAS   </a>
		</div>
		<div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'Autores' %}"><br>AUTORES</a>
		  </div>
		  <div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'login' %}"><br>LOGIN</a>
		  </div>
		
	  </div>
	</div>

        
<!--valores para ediar del modelo de autores-->
    {% block content %}
    <h1>Editar Autores</h1>
    <form action="" method="post">{% csrf_token %} 
        {{form.as_p}}
    <input type="submit" value="Guardar" id="btn_guardar"> 
    </form>
    {%endblock content %}
    
    
    
</body>
</html>

templates/registrar.html
{% load static %}
<!DOCTYPE html>
<html>
	<style>
		#texto{
			background-color: rgb(138, 1, 108);
			color: wheat;
		}

	

		#a_1{
			width: 100%;
			height: 100px;
			font-size: 20px;
			text-align: center;
			color: white;
			margin-top: 10px;
		}
		#a_1_1{
			width: 100%;
			height: 100px;
			font-size: 20px;
			text-align: center;
			color: black;
			margin-top: 10px;
		}
		#cont1{
			background-color: black;
			height: 50px;
		
		}

		#btn1{
			height: 130px;
			margin-top: -65px;
			border-style: solid;
		}

		#btn1_1{
			height: 130px;
			margin-top: -65px;
			background-color: yellow;
		}

		#btn1:hover{
			background-color: yellow;
			border-style: none;
		}
		#a_1:hover{
			color: #000;
		}
		#a_1_1{
			background-color: yellow;
		}
		.carousel-inner img{
			width: 100px;
			height: 400px;
		}

		#carouselExampleIndicators{
			width: 1200px;
			margin-left: 100px;
		}
		#promo{
			background-color: rgba(74, 63, 100, 0.363);
			width: 400px;
			height: 450px;
			float: left;
			border-style: solid;
		}
		#home_img{
			height: 200px;
			width: 150px;
			margin-left: 120px;
		}
		#content_lib{
			
			width: 1200px;
			
			margin-left: 100px;
			margin-top: 10px;
			
		}
		#link_desc{
			margin-left: 110px;

		}
		#linea{
			background-color: black;
			height: 40px;
			width: 100%;
			
		}

		#li_titulo_bd{
			font-family: Arial, Helvetica, sans-serif;
			font-size: 20px;
			font-weight: 400;
			text-align: center;
			list-style: none;
			color: black;
		}

        #cont{
        margin-left: 400px;
    }
    #id_username, #id_password1{
        width: 300px;
        height: 30px;
    }

    #titulo{
       margin-left: -400px;
    }
    #botonsusecc{
        width: 100px;
        margin-left: 150px;
    }
		
    #id_telefono{
        margin-left: 10px;
        width: 300px;
        height: 30px;
    }
    #id_edad{
        margin-left: 35px;
        width: 300px;
        height: 30px;
    }
    ul li,.helptext{
        color: white;
    }
	#saludo{
			color: white;
			text-align: center;
			margin-top: 20px;
		}
		#logout{
			
			margin-left: 70px;
		}
	</style>
<head>
	<title></title>
</head>
<!--link de css,bootstrap-->
<meta charset="UTF-8">
<meta http-equiv="X-UA_Compatible" content="IE-edge">
<meta name="viewport" content="wisth=device-width, initial-scale=1.0">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<body>

<!--menu-->
	<div class="jumbotron text-center" id="texto">
	  <h1>Libreria "Momentos"</h1>
	  <p>Encuentra lo que ves en tus sueños!!!!</p>
	</div>
	
	<div class="jumbotron" id="cont1">
	  <div class="row" >
		<div class="col-sm-2" id="btn1_1">
		 
		   <a id="a_1_1" type="button" class="btn" href="{% url 'home' %}"><br>HOME</a>
		</div>
		<div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'mangas' %}"><br>MANGAS</a>
		</div>
		<div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'revistas' %}"><br>REVISTAS   </a>
		</div>
		<div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'Autores' %}"><br>AUTORES</a>
		  </div>
		  <div class="col-sm-2" id="btn1">
			<a id="a_1" type="button" class="btn" href="{% url 'login' %}"><br>LOGIN</a>
		  </div>
		  <div class="col-sm-2" id="btn1">
			{% block contect %}
			  {% if user.is_authenticated %}
				  <h4 id="saludo">Bienvenido {{ user.username }}</h2>
				  <a id="logout" href="{% url 'logout' %}">log out</a>
				  {% endif %}
  
				  {% endblock contect%}
  
	  </div>
	  </div>
	</div>
<!--link para registrar el usario-->
<div id="cont">
    {% block content %}
    <h2 id="titulo">Registrar</h2>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn btn-success">Guardar</button>
        <br><br><br><br>
    </form>

{% endblock content%}
</div>


</body>
</html>